In [1]:
import pandas as pd
import numpy as np
import random
import math
from itertools import permutations

In [2]:
# COUNT Completion Time of sequence of order in flowshop schedule
def count_completion_time(processing_times):
    process_accumlutaion = np.zeros(processing_times.shape)
    accumulation_time = 0
    for i in range(len(processing_times[0])):
        accumulation_time += processing_times[0][i]
        process_accumlutaion[0][i] = accumulation_time

    for i in range(1, len(processing_times)):
        accumulation_time = process_accumlutaion[i-1][0]
        for j in range(len(processing_times[i])):
            if(j == 0):
                accumulation_time += processing_times[i][j]
            else:
                if(process_accumlutaion[i-1][j] < process_accumlutaion[i][j-1]):
                    accumulation_time += processing_times[i][j]
                else:
                    accumulation_time = process_accumlutaion[i-1][j]
                    accumulation_time += processing_times[i][j]
            process_accumlutaion[i][j] = accumulation_time
    return accumulation_time

In [3]:
def generate_random_sequence(n):
  """Generates a random sequence of numbers from 1 to n."""
  sequence = random.sample(range(1, n+1), n)  # Sample 6 unique numbers from range 1 to 6
  return sequence # return list

In [4]:
def sequence_to_string(sequence):
  """Converts a sequence of numbers to a string.
  Args:
      sequence: A tuple of integers representing the sequence.

  Returns:
      A string representation of the sequence.
  """
  return ''.join(map(str, sequence))

In [5]:

def generate_all_possibilites(data):
    numbers = range(1, 7)  # Create a sequence from 1 to 6

    # Use permutations to generate all possible orderings
    all_sequences = list(permutations(numbers))

    # Convert to List of String
    seq = [sequence_to_string(seq) for seq in all_sequences]
    
    sol = dict()
    for x in range(len(seq)):
        seq_list = np.zeros(data.shape)
        for i in range(len(seq[x])):
            seq_list[i] = data[int(seq[x][i])-1]
        sol.update({seq[x]: count_completion_time(seq_list)})
    return sol


In [6]:
def generate_random_solution(data, amount_of_solution):
    sol = dict()
    number_of_job = len(data)-1
    print(number_of_job)
    while len(sol) < amount_of_solution:  # Loop until desired number of solutions is reached
        seq = generate_random_sequence(number_of_job)
        seq_str = "-".join(map(str, seq))
        if seq_str not in sol:  # Check for uniqueness before adding to dictionary
            seq_list = np.zeros(data.shape)
            for i in range(len(seq)):
                seq_list[i] = data[(seq[i])-1]
            sol.update({seq_str: count_completion_time(seq_list)})
    return sol

In [7]:
# def generate_random_solution(data, amount_of_solution):
#     sol = dict()
#     number_of_job = len(data)-1
#     while len(sol) < amount_of_solution:  # Loop until desired number of solutions is reached
#         seq = generate_random_sequence(number_of_job)
#         print(seq)
#         seq_list = np.zeros(data.shape)
#         for i in range(len(seq)):
#             seq_list[i] = data[int(seq[i])-1]
#         sol.update({seq: count_completion_time(seq_list)})
#         # if seq not in sol:  # Check for uniqueness before adding to dictionary
#     return sol

In [8]:
def min_max_normalization(arr):
    min_val = np.min(arr) -1 # (np.min(arr)  * 1/100)
    max_val = np.max(arr)
    return (arr - min_val) / (max_val - min_val)

In [9]:
# Z-Score Normalization 
def zscore_normalization(arr):
    mean_val = np.mean(arr)
    std_dev = np.std(arr)
    return (arr - mean_val) / std_dev


In [10]:
def find_up_low_bound(arr):
    max_val = np.max(arr)
    min_val = np.min(arr)
    up_bound = math.ceil(max_val)
    low_bound = math.floor(min_val)
    return low_bound, up_bound

In [11]:
def sort_by_index(data):
  """Sorts a list and returns the corresponding sorted index sequence.

  Args:
      data: A list of sortable elements.

  Returns:
      A list of indices representing the sorted order of the original list.
  """
  return sorted(range(len(data)), key=lambda i: data[i])


### RUN

In [25]:
# Read The Data
# For data-0
# data = pd.read_csv("data/data0.csv")
# For data-1
# data = pd.read_csv("data/data1.csv")
# For data-2
# data = pd.read_csv("data/data2.csv")
# For data-3
data = pd.read_csv("data/data3.csv")

In [26]:
#LOAD DATA

data = data.values
data = data[:, 1:]
data

array([[89.06, 131.84, 419.34, 155.12, 284.79, 76.38],
       [150.7, 220.96, 638.86, 262.28, 478.7, 130.84],
       [160.56, 244.12, 707.76, 279.16, 532.8, 135.08],
       [323.4, 484.52, 1545.0, 562.24, 1056.68, 274.64],
       [565.02, 751.9, 2431.32, 975.14, 1679.08, 313.4]], dtype=object)

In [27]:
# INIT THE PARAMETERS
population_size = 10
iteration_ = 100
gamma = 0.01
alpha = 0.1
beta = 0.2
delta = 0.97

In [28]:
# Generate Random Solution based on population_size
solution_ = generate_random_solution(data=data, amount_of_solution=population_size)

In [96]:
# RUN THIS FOR ALL POSSIBILITIES
# population_size=100
# solution_ = generate_all_possibilites(data=data)

In [29]:
solution_

{'4-1-2-3': 5403.21,
 '1-2-4-3': 5110.900000000001,
 '3-2-4-1': 5276.39,
 '3-4-1-2': 5170.6900000000005,
 '4-1-3-2': 5398.97,
 '4-3-1-2': 5398.97,
 '3-1-2-4': 5609.200000000001,
 '1-3-4-2': 5121.46,
 '2-1-3-4': 5576.18,
 '2-3-1-4': 5576.18}

In [98]:
solution_keys = list(solution_.keys())
solution_list = list(solution_.values())
solution_list = np.array(solution_list)

In [99]:
solution_list

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

In [100]:
normalize_solution = zscore_normalization(solution_list)

In [101]:
normalize_solution

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

In [102]:
low_bound, up_bound  = find_up_low_bound(normalize_solution)

ValueError: cannot convert float NaN to integer

In [ ]:
# CREATE OBJECT AND RUN ALGORITHM
from firefly import firefly_algo

In [ ]:
fa = firefly_algo(data=normalize_solution, population=population_size, max_iter=iteration_, low_bound=low_bound, up_bound=up_bound, gamma=gamma, alpha=alpha, beta=beta, delta=delta)
fa.run()

In [ ]:
fa.print_result()


-45.756
0.375
0.307
0.492
-79.221
0.173
-63.274
-26.322
1.430
1.250


In [ ]:
sorted_indices = sort_by_index(normalize_solution)

In [ ]:
res = dict()
for i in sorted_indices:
    solution_key_list = f"{solution_keys[i]} - {solution_list[i]}";
    res.update({solution_key_list: fa.data[i]})

In [ ]:
res

{'14-13-9-6-7-10-11-16-2-3-12-8-15-5-1-4 - 34858.36': -79.2213731476391,
 '3-6-2-1-9-11-10-8-13-16-4-5-12-15-7-14 - 38180.119999999995': -63.27405489003178,
 '12-1-9-16-15-4-5-3-2-6-14-8-10-7-11-13 - 39918.15': -45.756263216870956,
 '5-15-3-12-7-14-10-1-11-16-2-4-13-6-8-9 - 39349.780000000006': -26.322326304076082,
 '1-5-16-13-15-6-7-14-11-10-4-3-2-12-9-8 - 41498.44': 0.17345280262783208,
 '15-9-14-2-3-11-16-7-8-5-10-6-1-4-13-12 - 41886.18': 0.307208934984494,
 '2-12-14-8-5-15-3-4-7-16-11-13-1-10-6-9 - 42083.18': 0.37516673679566265,
 '9-10-11-13-16-6-5-15-8-7-14-1-2-12-3-4 - 42422.939999999995': 0.49237152229496367,
 '11-2-4-16-13-12-1-6-8-14-10-9-7-3-5-15 - 44619.5': 1.2501044621241055,
 '2-16-6-7-9-4-1-3-5-14-12-13-10-15-11-8 - 45139.600000000006': 1.4295199581748121}